### PR TITLE
Feature website nginx vhost params

### PR DESCRIPTION
**Pull request by bartjanssens92**
Using the custom defined types for creating vhosts in nginx is good for easy setups, sadly it would mean that building more complex vhosts is now impossible. First iteration tried to add logic to build a config hash to pass to the nginx::resource::server type but this would grow very complex. Instead opted to add a flag so one can toggle between more generic vhost config generated by the profiles module itself or straight use the nginx module defined type so one can pass more options. By default it will still use the type defined within the profiles to not break setups that have switched over.

### CODE REVIEW

**Comment by attachmentgenie** [comment]
i have been struggling with how to solve this problem, by either just adding the missing parameters and  hereby just rebuilding the upstream defined type (not ideal). Puppet lacking variable argument lists (to bad). So i have been pondering a similar solution. 

However is prefer to reverse the if statement and designating the defined type from this module being the standard/norm. And allowing the upstream defined type behind a $upstream_defined_type flag

would you be able to make this change?

**Comment by bartjanssens92** [comment]
Agreed, it is a dificult issue to solve. One could go via a hash that could contain all the params but does run into issues when trying to set parameters where defaults are asked. You can pass that hash to the defined type using the statement below but the main issue is getting that hash containing the parameters to be good.
```
$_vhosts_parameters = {
  'www_root' => '/var/vhosts',
  'listen_port' => 80,
  'some_other' => 'parameter',
}

::nginx::resource::server { $name:
  * => $_vhosts_parameters,
}
```

**Review by attachmentgenie — APPROVED** [review]

**Comment by attachmentgenie** [comment]
thanks!

**Comment by bartjanssens92** [comment]
Awesome :) Thnx

**Pull request merged**
